# Generated by Django 5.1.2 on 2024-11-06 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_alter_kolo_date_alter_kolo_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kolo',
            new_name='Seminar',
        ),
    ]
