# Generated by Django 5.1.2 on 2024-11-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_rename_kolo_seminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lead', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_difficulty', models.IntegerField(blank=True, null=True)),
                ('discord_role_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='level',
            new_name='difficulty',
        ),
        migrations.AddField(
            model_name='seminar',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='special_guest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='theme',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seminars.seminargroup'),
        ),
    ]
