# Generated by Django 5.1.3 on 2024-12-26 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_alter_seminar_date_alter_seminar_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seminar',
            name='seminars_se_date_a108ff_idx',
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['date', 'time'], name='seminars_se_date_98d5d1_idx'),
        ),
    ]
