# Generated by Django 5.1.3 on 2025-01-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_remove_seminar_seminars_se_date_a108ff_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
