# Generated by Django 5.1.3 on 2025-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_seminargroup_discord_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='discord_voice_channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='discord_voice_channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
