# Generated by Django 5.1.2 on 2025-03-13 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0010_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seminars.googleformstemplate'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['date_time'], name='reminder_index'),
        ),
    ]
