# Generated by Django 5.1.2 on 2024-12-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_alter_post_authors_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
