# Generated by Django 5.1.2 on 2024-12-18 16:18

from django.db import migrations, models


def move_text_to_content(apps, schema_editor):
    Post = apps.get_model('mainSite', 'Post')

    for post in Post.objects.all():
        post.content = (post.text_field_1 or '') + '\n\n' + (post.text_field_2 or '')
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_alter_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.RunPython(move_text_to_content),
        migrations.RemoveField(
            model_name='post',
            name='text_field_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_field_2',
        ),
    ]
