# Generated by Django 5.1.3 on 2024-12-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_problem_counter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='linkedaccount',
            name='accounts_li_externa_ed775c_idx',
        ),
        migrations.AddIndex(
            model_name='activityscore',
            index=models.Index(fields=['user', 'timestamp'], include=('change',), name='activity_score_index'),
        ),
    ]
